import "./globals.css";
import { GlobalProvider } from "./GlobalProvider";
import Navbar from "../components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/Footer";
import localFont from 'next/font/local'

const getCategories = async () => {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/category`,{cache:'no-store'});
  if (!res.ok){
    throw new Error("Failed to fetch data")
  }
  return res.json()
}

const myFont = localFont({
  src: [
    {
      path: '../public/fonts/futur.ttf',
      weight: '400',
      style: 'bold',
    },
    {
      path: '../public/fonts/Futura Bold Italic font.ttf',
      weight: '400',
      style: 'bold_italic',
    },
    {
      path: '../public/fonts/futura light bt.ttf',
      weight: '400',
      style: 'light',
    },
    {
      path: '../public/fonts/Futura-CondensedLight.otf',
      weight: '400',
      style: 'condensed',
    },
    {
      path: '../public/fonts/futura medium bt.ttf',
      weight: '400',
      style: 'medium',
    },
    {
      path: '../public/fonts/Futura Light font.ttf',
      weight: '400',
      style: 'futura-lt',
    },
  ],
  variable: '--font-futura',

})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const myFont = localFont({ src: './fonts/Futura-CondensedLight.ttf' })
export default async function RootLayout({ children }) {
  const categories = await getCategories()
  return (
    <html lang="en" className={`${myFont.variable} font-futura`}>
      <ClerkProvider>
        <body>
          <GlobalProvider>
            <Navbar categories={categories} />
            {children}
            <Footer />
          </GlobalProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
