import "./globals.css";
import { GlobalProvider } from "./GlobalProvider";
import Navbar from "../components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <GlobalProvider>
            <Navbar />
            {children}
          </GlobalProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
